### ISSUE TITLE
sometimes the game just suddenly terminated itself with nothing at charlatano consonle

### ISSUE THREAD

**Issue by wuwujia** [Jire/Charlatano#265]
sometimes the game just suddenly terminated itself with nothing showing at charlatano consonle

and sometimes the console shows codes downbelow:

Exception in thread "Thread-11" kotlin.KotlinNullPointerException
        at com.charlatano.game.entity.BombKt.location(Bomb.kt:51)
        at com.charlatano.scripts.BombTimerKt$bombTimer$$inlined$invoke$1.invoke(Every.kt:41)
        at com.charlatano.scripts.BombTimerKt$bombTimer$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by wuwujia** [comment]
BTW I am using Win10 x64, a VPN to CSGO gaming.
Is that something wrong with VPN?

**Comment by adelduprat** [comment]
Disable the bomb timer script.

**Comment by MrSugerRush** [comment]
I don't use a VPN and I get the same problems.
I'm pretty sure the bomb timer doesn't work on windows 10, but it should be fixed in 1.0.6
The game crashing is something I experience as well, however I could not find a fix for this, and hopefully there will be one in the next update.
So no, your VPN is working fine, and like adelduprat said "Disable the bomb timer script."

**Comment by wuwujia** [comment]
@MrSugerRush @adleduprat
Pretty damn sure I am using deffault settings as I downloaded the zip and built days ago.
How to disable the bomb timer script then?>

**Comment by wuwujia** [comment]
@MrSugerRush @adelduprat
Pretty damn sure I am using deffault settings as I downloaded the zip and built days ago.
How to disable the bomb timer script then?>

**Comment by wuwujia** [comment]
@MrSugerRush @adelduprat
Pretty damn sure I am using default settings as I downloaded the zip and built days ago.
How to disable the bomb timer script then?>

**Comment by adelduprat** [comment]
Actually, scratch that. I've disabled the bomb timer and I'm still getting crashes. I'm pretty sure I've found the root cause, though.

Go to `src\main\kotlin\com\charlatano\Charlatano.kt` and remove `bombTimer()` from the code (line 51), then run `build.bat`. Make sure `ENABLE_BOMB_TIMER` is set to `false` in your `Scripts.kts` file.

**Comment by MoofMonkey** [comment]
Close please, outdated and working now.
